{{- if .Values.metrics.enabled }}
apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sre-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: sre-api

  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
{{- end }}