{{- if .Values.analyser.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-analyser
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.analyserClientId | quote }}
{{- end }}

{{- if .Values.collector.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-collector
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azure.collectorClientId | quote }}
{{- end }}