apiVersion: v1
kind: Service
metadata:
  name: sre-api
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sre-api
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP

{{- if .Values.collector.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: incident-collector
  namespace: {{ .Values.namespace }}
  labels:
    app: incident-collector
spec:
  selector:
    app: incident-collector
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: {{ .Values.collectorService.type }}
{{- end }}

{{- if .Values.analyser.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ai-analyser
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.analyserService.type }}
  selector:
    app: ai-analyser
  ports:
    - port: {{ .Values.analyserService.port }}
      targetPort: 8080
{{- end }}